# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Cache modules
        uses: actions/cache@v2
        env:
          cache-name: ${{ steps.extract_version.outputs.version }}
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            node_modules
          key: ${{ runner.os }}-socketmesh-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: |
          yarn install

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          yarn test
